### ISSUE TITLE
Why can't I have more than two characters in a literal token?

### ISSUE THREAD

**Issue by DaBlick** [smallhelm/tokenizer2#1]
Here's the the code
    var t = tokenizer2((token) => { console.log('token:', token);});

    t.addRule(/^[\s]$/, 'whitespace');
    t.addRule(/^[\S]$/, 'non-whitespace');
    t.addRule(/^lin$/, 'link');

    t.onText("Hi link");
    t.end();

Here's the output:

```
token: { type: 'non-whitespace', src: 'H', line: 1, col: 1 }
token: { type: 'non-whitespace', src: 'i', line: 1, col: 2 }
token: { type: 'whitespace', src: ' ', line: 1, col: 3 }
token: { type: 'non-whitespace', src: 'l', line: 1, col: 4 }
token: { type: 'non-whitespace', src: 'i', line: 1, col: 5 }
token: { type: 'non-whitespace', src: 'n', line: 1, col: 6 }
token: { type: 'non-whitespace', src: 'k', line: 1, col: 7 }
```

Notice that in the output, "lin" is matched as 3 "non-whitespace" tokens rather than as a "link" token.   I get the same result when I move the addRule for "lin" to the front.

Now when I modify the "link" rule to just have two literal characters instead of 3 as follows:

    t.addRule(/^li$/, 'link');

I get a "link" token:

```
token: { type: 'non-whitespace', src: 'H', line: 1, col: 1 }
token: { type: 'non-whitespace', src: 'i', line: 1, col: 2 }
token: { type: 'whitespace', src: ' ', line: 1, col: 3 }
token: { type: 'link', src: 'li', line: 1, col: 4 }
token: { type: 'non-whitespace', src: 'n', line: 1, col: 6 }
token: { type: 'non-whitespace', src: 'k', line: 1, col: 7 }
```

**Comment by farskipper** [comment]
Hi, I think this is what you want:
```js
t.addRule(/^link$/, 'link');
t.addRule(/^[\s]+$/, 'whitespace');
t.addRule(/^[\S]+$/, 'non-whitespace');
```
I added `+` to the whitespace and non-whitespace rules so they will match the longest sequence. And moved the link rule so it will match before the non-whitespace.

The algorithm works by adding one character at a time then testing all the regexps to see which one matches the longest sequence. So what was happening before when it parsed `"link"` it would match `"l"` to `[\S]` then add a character to see what it matches now `"li"`. No rule matched that. So it reverted to `"l"` then it continued parsing the rest of the string.

Now it matches like this
`l` -> `[\S]+`
`li` -> `[\S]+`
`lin` -> `[\S]+`
`link` -> `link`

**Comment by DaBlick** [comment]
So here's what I want for tokens described: "

"@{link"        
"|"   
"}"      
and... a wildcard rule  to match anything that doesn't match the others

That is "@{link", a bang, and a closing brace plus the wildcard.

Is there a way for me to get that wildcard to be something that doesn't start with an "@", a band or a closing brace"?  Or is there a  more elegant way to say "make a token out of anything that doesn't match the others?

**Comment by farskipper** [comment]
Sorry I forgot to get back to you. Currently there is not a catch-all. But you could try adding a regex that matches everything else i.e. something like `/$[^@]*$/` so that it won’t interfere with the beginning of a link.

Ironically I haven’t actually used this library in a while. Instead, I just tokenize things by creating a simple state machine with `while` loops. Here are 2 examples: [one](https://github.com/farskipper/ecmaless/blob/5503521ccb5c28b03fcb7bbeb3d6dd81e34e1e7a/packages/ecmaless-parser2/src/tokenizer.js#L79), [two](https://github.com/Picolab/node-krl-parser/blob/478df6033ad55f239d89be95c40936cbfaf07058/src/tokenizer.js#L32)

So for this case, you just have an outer `while` loop that reads along char by char until it sees `@{` then in a sub-loop continue to extract the link until you reach `}` then return to the main loop.
